:set number
:syntax on
:set ruler
:set t_Co=256
:set ls=2
:set mouse=a
:set tabstop=4
:set shiftwidth=4
:set expandtab
:set autoindent
:set smartindent

"Use 2 space indenting for ruby files.
au FileType ruby setl sw=2 sts=2 et
au FileType html setl sw=2 sts=2 et
set nocompatible

"Highlight searches, unhighlight with space
:set hlsearch
:nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR>
:filetype off

execute pathogen#infect()
execute pathogen#helptags()

"Open taglist window
nnoremap <silent> <C-\> :TlistToggle<CR>
"When opening taglist window, give it focus
let Tlist_GainFocus_On_ToggleOpen = 1
let Tlist_Exit_OnlyWindow = 1
let Tlist_Highlight_Tag_On_BufEnter = 1
let tlist_php_settings='php;c:class;f:function;d:constants;v:variables'

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_wq = 0

"Enable syntax checking on save
let g:syntastic_php_checkers = ['php', 'phpcs']
let g:syntastic_enable_signs=1
let g:syntastic_auto_loc_list=1

let g:netrw_liststyle=3

let g:vdebug_options = {
\ 'server': '0.0.0.0',
\ 'port': '000'
\}
let g:vdebug_options['path_maps'] = {
\ '/site/path/dev': '/site/path/host',
\}

"Enable filetype plugins, and remap the phpfolding update command to F7
map <F7> <Esc>:EnableFastPHPFolds<Cr>

:set guioptions -=m
:set guioptions -=T
colorscheme slate
let Tlist_Close_On_Select = 1

"Jump to recently visited line, but not if this is a commit message...
if has("autocmd") && expand('%:t') != 'COMMIT_EDITMSG'
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

:filetype plugin on

" Load matchit.vim, but only if the user hasn't installed a newer version.
if !exists('g:loaded_matchit') && findfile('plugin/matchit.vim', &rtp) ==# ''
  runtime! macros/matchit.vim
endif
